server:
  port: 9001
mybatis-plus:
  type-aliases-package: com.studio.common.model.pojo
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: iChat-chat-9001
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iChat?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    #    url: jdbc:mysql://rm-7xvah021798y6e1dd4o.mysql.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT      binbini Chang687501
    username: root
    password: Chang687501
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-wait: 100000
          max-idle: 10
          max-active: 100
      timeout: 5000
  rabbitmq:
    host: 8.134.94.102
    port: 5672
    username: guest
    password: guest
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#  mail:
#    port: 465
#    default-encoding: UTF-8
#    host: smtp.qq.com
#    username: 847024724@qq.com
#    password: lirgpizxrpscbdaj
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#          auth: true
#          starttls:
#            enable: true
#            required: true
info:
  app.name: 603.studio.com
  company.name: 603.studio.com
login:
  pre: LOGIN
  expire: 1800
pic:
  dir: /root/data/images/
