server:
  port: 9000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iChat?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: Chang687501

mybatis-plus:
  type-aliases-package: com.studio.common.model.pojo

logging:
  level:
    com: debug

# 下面几个是自定义的，rsa也是自定义的
rsa:
  key:
    pubKeyPath: /Users/binbini/Documents/workspace/iChat/iChat-serve/auth_key/id_key_rsa.pub
    priKeyPath: /Users/binbini/Documents/workspace/iChat/iChat-serve/auth_key/id_key_rsa