server:
  port: 9000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.12.23:3306/iChat?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: As603888

mybatis-plus:
  type-aliases-package: com.studio.common.model.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com: debug

# 下面几个是自定义的，rsa也是自定义的
rsa:
  key:
    pubKeyPath: /Users/binbini/Documents/workspace/iChat/iChat-serve/auth_key/id_key_rsa.pub
    priKeyPath: /Users/binbini/Documents/workspace/iChat/iChat-serve/auth_key/id_key_rsa
#rsa:
#  key:
#    pubKeyPath: /root/data/auth_key/id_key_rsa.pub
#    priKeyPath: /root/data/auth_key/id_key_rsa