server:
  port: 9002
  servlet:
    context-path: /pic
spring:
  application:
    name: image-9002
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
pic:
  dir: /root/data/images/
rsa:
  key:
    pubKeyPath: /root/data/auth_key/id_key_rsa.pub


